In [2]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import (
    StandardScaler,
    OrdinalEncoder,
    LabelEncoder,
    OneHotEncoder
)
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

from sklearn.linear_model import LinearRegression, Ridge,Lasso,LogisticRegression
from sklearn.neighbors import KNeighborsRegressor

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor,AdaBoostRegressor
from sklearn.ensemble import ExtraTreesRegressor

from sklearn.model_selection import train_test_split, GridSearchCV,cross_validate, cross_val_predict
# Scikit-learn: Metrics
from sklearn.metrics import r2_score, mean_squared_error

In [3]:
path="/Users/ritabratadas/Desktop/STUDY FOLDERS/Machine Learning/PROJECTS/DATASETS/taxi_fare_train.csv"
df=pd.read_csv(path)

In [4]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,extra,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee
0,0,2023-06-28 17:31:46,2023-06-28 18:22:12,1.0,1.50,1.0,N,212,237,Credit Card,5.0,6.533210,0.0,1.0,24.80,2.5,0.0
1,0,2023-06-29 19:15:55,2023-06-29 19:07:31,1.0,3.80,1.0,N,6,163,Credit Card,5.0,9.187048,0.0,1.0,31.55,2.5,0.0
2,1,2023-06-30 18:28:50,2023-06-30 18:01:19,2.0,1.89,1.0,N,35,81,Credit Card,2.5,6.793777,0.0,1.0,24.84,2.5,0.0
3,1,2023-06-30 22:57:37,2023-06-30 22:55:34,1.0,1.10,1.0,N,46,99,Credit Card,1.0,3.695121,0.0,1.0,13.45,2.5,0.0
4,1,2023-06-28 18:39:16,2023-06-28 17:31:29,2.0,2.84,1.0,N,213,114,Credit Card,2.5,7.838753,0.0,1.0,29.88,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1,2023-06-28 16:38:27,2023-06-28 17:02:20,1.0,3.31,1.0,N,201,55,Cash,2.5,2.195433,0.0,1.0,22.10,2.5,0.0
9996,1,2023-06-30 15:59:37,2023-06-30 17:43:59,1.0,1.22,1.0,N,221,143,Credit Card,2.5,9.137115,0.0,1.0,21.45,2.5,0.0
9997,1,2023-06-29 09:26:14,2023-06-29 11:22:26,1.0,1.31,1.0,N,161,150,Credit Card,0.0,5.940952,0.0,1.0,17.29,2.5,0.0
9998,1,2023-06-30 17:43:41,2023-06-30 17:46:22,1.0,0.89,1.0,N,120,191,Cash,2.5,3.233409,0.0,1.0,13.70,2.5,0.0
9999,1,2023-06-29 21:54:57,2023-06-29 22:25:39,,0.64,,,111,36,Wallet,0.0,3.674585,0.0,1.0,14.25,,

In [5]:
# remove all white space globally 


df = df.replace(r'^\s*$', np.nan, regex=True)

In [6]:
df.columns

Index(['VendorID', ' tpep_pickup_datetime', ' tpep_dropoff_datetime',
       ' passenger_count', ' trip_distance', ' RatecodeID',
       ' store_and_fwd_flag', ' PULocationID', ' DOLocationID',
       ' payment_type', ' extra', ' tip_amount         ', ' tolls_amount',
       ' improvement_surcharge', ' total_amount', ' congestion_surcharge',
       ' Airport_fee'],
      dtype='object')

In [7]:
df.columns = df.columns.str.strip()

In [8]:
X=df.drop(columns="total_amount",axis=1)

In [9]:
X

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,extra,tip_amount,tolls_amount,improvement_surcharge,congestion_surcharge,Airport_fee
0,0,2023-06-28 17:31:46,2023-06-28 18:22:12,1.0,1.50,1.0,N,212,237,Credit Card,5.0,6.533210,0.0,1.0,2.5,0.0
1,0,2023-06-29 19:15:55,2023-06-29 19:07:31,1.0,3.80,1.0,N,6,163,Credit Card,5.0,9.187048,0.0,1.0,2.5,0.0
2,1,2023-06-30 18:28:50,2023-06-30 18:01:19,2.0,1.89,1.0,N,35,81,Credit Card,2.5,6.793777,0.0,1.0,2.5,0.0
3,1,2023-06-30 22:57:37,2023-06-30 22:55:34,1.0,1.10,1.0,N,46,99,Credit Card,1.0,3.695121,0.0,1.0,2.5,0.0
4,1,2023-06-28 18:39:16,2023-06-28 17:31:29,2.0,2.84,1.0,N,213,114,Credit Card,2.5,7.838753,0.0,1.0,2.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1,2023-06-28 16:38:27,2023-06-28 17:02:20,1.0,3.31,1.0,N,201,55,Cash,2.5,2.195433,0.0,1.0,2.5,0.0
9996,1,2023-06-30 15:59:37,2023-06-30 17:43:59,1.0,1.22,1.0,N,221,143,Credit Card,2.5,9.137115,0.0,1.0,2.5,0.0
9997,1,2023-06-29 09:26:14,2023-06-29 11:22:26,1.0,1.31,1.0,N,161,150,Credit Card,0.0,5.940952,0.0,1.0,2.5,0.0
9998,1,2023-06-30 17:43:41,2023-06-30 17:46:22,1.0,0.89,1.0,N,120,191,Cash,2.5,3.233409,0.0,1.0,2.5,0.0
9999,1,2023-06-29 21:54:57,2023-06-29 22:25:39,NaN,0.64,NaN,NaN,111,36,Wallet,0.0,3.674585,0.0,1.0,NaN,NaN

In [10]:
i=(X["store_and_fwd_flag"].unique()[1])

In [11]:
X["store_and_fwd_flag"] = X["store_and_fwd_flag"].replace(i, X["store_and_fwd_flag"].unique()[0])

In [12]:
X["store_and_fwd_flag"].value_counts()

store_and_fwd_flag
N                     9931
Y                       69
Name: count, dtype: int64

In [13]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               10000 non-null  int64
 1   tpep_pickup_datetime   10000 non-null  object
 2   tpep_dropoff_datetime  10000 non-null  object
 3   passenger_count        9634 non-null   object
 4   trip_distance          10000 non-null  float64
 5   RatecodeID             9634 non-null   object
 6   store_and_fwd_flag     10000 non-null  object
 7   PULocationID           10000 non-null  int64
 8   DOLocationID           10000 non-null  int64
 9   payment_type           10000 non-null  object
 10  extra                  10000 non-null  float64
 11  tip_amount             10000 non-null  float64
 12  tolls_amount           10000 non-null  float64
 13  improvement_surcharge  10000 non-null  float64
 14  congestion_surcharge   9634 non-null   object
 15  Airport_fee            9634 non-null   object
dtypes: float64(5), int64(3), object(8)
memory usage: 1.2+ MB

In [14]:
y=df["total_amount"]

In [15]:
y.head()

0    24.80
1    31.55
2    24.84
3    13.45
4    29.88
Name: total_amount, dtype: float64

In [16]:
# different types of columns
num_cols = [
    "trip_distance",
    "extra",
    "tip_amount",
    "tolls_amount",
    "improvement_surcharge"
]

num_like_cols = [
    "passenger_count",
    "RatecodeID",
    "congestion_surcharge",
    "Airport_fee"
]


date_cols = [
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime"
]

In [17]:
le=LabelEncoder()
X["store_and_fwd_flag"]=le.fit_transform(X["store_and_fwd_flag"])
X["payment_type"]=le.fit_transform(X["payment_type"])

In [18]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               10000 non-null  int64
 1   tpep_pickup_datetime   10000 non-null  object
 2   tpep_dropoff_datetime  10000 non-null  object
 3   passenger_count        9634 non-null   object
 4   trip_distance          10000 non-null  float64
 5   RatecodeID             9634 non-null   object
 6   store_and_fwd_flag     10000 non-null  int64
 7   PULocationID           10000 non-null  int64
 8   DOLocationID           10000 non-null  int64
 9   payment_type           10000 non-null  int64
 10  extra                  10000 non-null  float64
 11  tip_amount             10000 non-null  float64
 12  tolls_amount           10000 non-null  float64
 13  improvement_surcharge  10000 non-null  float64
 14  congestion_surcharge   9634 non-null   object
 15  Airport_fee            9634 non-null   object
dtypes: float64(5), int64(5), object(6)
memory usage: 1.2+ MB

In [19]:
from sklearn.base import BaseEstimator, TransformerMixin

In [20]:
# custom transformer for date and time
class DateFeatureExtractor(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        self.cols_ = X.columns   # store column names
        return self
    
    def transform(self, X):
        X = X.copy()
        
        for col in self.cols_:
            X[col] = pd.to_datetime(X[col])
            X[col + "_hour"] = X[col].dt.hour
            X[col + "_day"] = X[col].dt.day
            X[col + "_weekday"] = X[col].dt.weekday
        
        # drop ONLY original date columns
        return X.drop(columns=self.cols_)

In [21]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=1)

In [22]:
num_pipeline=Pipeline([
    ("imputer",SimpleImputer(strategy="median")),
    ("scaler",StandardScaler())
])

date_pipeline = Pipeline([
    ("date_features", DateFeatureExtractor())
])

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_cols),
    ("num_like", num_pipeline, num_like_cols),
    ("date", date_pipeline, date_cols)
])

# pipeline = Pipeline([
#     ("preprocessing", preprocessor),
#     ("model",RandomForestRegressor())
# ])

In [23]:

from sklearn.svm import SVR

models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso(),
    "RandomForest": RandomForestRegressor(),
    "GradientBoosting": GradientBoostingRegressor(),
    "SVR": SVR(),
    "KNN": KNeighborsRegressor()
}

In [24]:
from sklearn.pipeline import Pipeline
from sklearn.metrics import root_mean_squared_error

results = {}

for name, model in models.items():
    pipe = Pipeline([
        ("preprocessing", preprocessor),
        ("model", model)
    ])
    
    pipe.fit(X_train, y_train)
    preds = pipe.predict(X_test)
    
    rmse = root_mean_squared_error(y_test, preds)
    r2=r2_score(y_true=y_test,y_pred=preds)
    results[name] = r2

    
    print(f"{name}:  RMSE error = {rmse}    r2_score = {r2}")
    print("="*100)

LinearRegression:  RMSE error = 10.703317276321144    r2_score = 0.8445444240176379
====================================================================================================
Ridge:  RMSE error = 10.702549885550512    r2_score = 0.8445667144710827
====================================================================================================
Lasso:  RMSE error = 10.9762011040908    r2_score = 0.8365166168148939
====================================================================================================
RandomForest:  RMSE error = 8.52283553541113    r2_score = 0.9014315967005143
====================================================================================================
GradientBoosting:  RMSE error = 7.925494594712899    r2_score = 0.9147641583685525
====================================================================================================
SVR:  RMSE error = 20.54873113058339    r2_score = 0.42701991843416787
====================================================================================================
KNN:  RMSE error = 12.944164541341916    r2_score = 0.7726381704254235
====================================================================================================

In [25]:
pipe

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['trip_distance', 'extra',
                                                   'tip_amount', 'tolls_amount',
                                                   'improvement_surcharge']),
                                                 ('num_like',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['passenger_count',
                                                   'RatecodeID',
                                                   'congestion_surcharge',
                                                   'Airport_fee']),
                                                 ('date',
                                                  Pipeline(steps=[('date_features',
                                                                   DateFeatureExtractor())]),
                                                  ['tpep_pickup_datetime',
                                                   'tpep_dropoff_datetime'])])),
                ('model', KNeighborsRegressor())])

In [26]:
import matplotlib.pyplot as plt

# results = {"ModelName": rmse, ...}

plt.figure()
bars = plt.bar(names, scores)

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval, f"{yval:.2f}",
             ha='center', va='bottom')

plt.xlabel("Models")
plt.ylabel("r2_score")
plt.title("Model Comparison")

plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

NameError: name 'names' is not defined

## Hyperparameter tuning